name: Laravel Workflow
on:
    workflow_dispatch:
        inputs:
            name:
                description: "enter your name"
                required: true
                default: "tuhin"
                     
   
jobs:
  first-workflow:
    runs-on: ubuntu-latest
    outputs:
        var1: ${{ steps.xxx.outputs.y }}
        

    steps:
        - name: Generating_name
          id: xxx
          run: echo "y=Hi ,${{ github.event.inputs.name }}" >> $GITHUB_OUTPUT
        
       



  second-workflow:
    runs-on: ubuntu-latest
    needs: first-workflow
    steps:
         - name: myNameShowing
           run: echo "${{ needs.first-workflow.outputs.var1 }}"
            


