name: mainBranch_workflow444
on:
   workflow_dispatch:
jobs:
  first-workflow:
    runs-on: ubuntu-latest

    steps:
        - name: 'mainBranch4444'
          run: echo 'mainBranch 4444'
        - name: 'mycorn5555'
          run: echo 'mainBranch 5555' 
  second-workflow:
    runs-on: 'windows'
    needs: first-workflow
    steps:
         - name: ndJobSteps=666666
           run: echo 'fuck...'       


