name: mainBranch_workflow2
on:
    push:
        branches:
            - main
jobs:
  first-job:
    runs-on: windows-latest

    steps:
        - name: 'mainBranch4'
          run: echo 'mainBranch 4'
        - name: 'mycorn5'
          run: echo 'mainBranch 5' 
  Second-job:
    runs-on: 'windows'
    steps:
         - name: ndJobSteps 1
           run: echo 'fuck...'       


