name: mainBranch_workflow2
on:
   workflow_dispatch:
jobs:
  first-workflow:
    runs-on: windows-latest

    steps:
        - name: 'mainBranch4'
          run: echo 'mainBranch 4'
        - name: 'mycorn5'
          run: echo 'mainBranch 5' 
  second-workflow:
    runs-on: 'windows'
    needs: first-workflow
    steps:
         - name: ndJobSteps=111
           run: echo 'fuck...'       


