name: mainBranch_workflow33
on:
   workflow_dispatch:
jobs:
  first-workflow:
    runs-on: ubuntu-latest

    steps:
        - name: 'mainBranch44'
          run: echo 'mainBranch 44'
        - name: 'mycorn55'
          run: echo 'mainBranch 55' 
  second-workflow:
    runs-on: 'windows'
    needs: first-workflow
    steps:
         - name: ndJobSteps=666
           run: echo 'fuck...'       


