name: first_workflow
on:
    workflow_dispatch:
jobs:
  first-job:
    runs-on: 'ubuntu-latest'
    steps:
        - name: 'fuck4'
          run: echo 'hello world 4'
        - name: 'fuck5'
          run: echo 'hello world 5' 


