name: corn_workflow
on:
    schedule:
        - cron: '*/2 * * * *'
jobs:
  first-job:
    runs-on: 'ubuntu-latest'
    steps:
        - name: 'mycorn4'
          run: |
            echo 'corn world 4'
            echo 'corn world 5'
        - name: 'mycorn5'
          run: echo 'corn world 6' 


